2021-spring PBL course
cgrhyu/cgrhyu.github.io pull request #22
Opened 2021-07-15 08:12 UTC by DiKaliZy

2021-spring PBL course page update

2021-07-15 08:21 UTC, thscowns commented on courses/2021-spring-pbl.md
> +title: COMPUTER SCIENCE Capstone PBL(Physically-Based Character Simulation) - 2020 Spring
2021 spring으로 바뀌어야 할 것 같습니다.

2021-07-15 21:39 UTC, yssl requested changes

2021-07-15 21:39 UTC, yssl commented on 3-courses.md
> +<li><a href="courses/2021-spring-pbl.html">PBL4001 COMPUTER SCIENCE Capstone PBL(Physically-Based Character Simulation)</a></li>
부제가 작년과는 달라졌습니다. 확인해서 수정하기 바랍니다.

2021-07-15 21:39 UTC, yssl commented on courses/2021-spring-pbl.md
> +title: COMPUTER SCIENCE Capstone PBL(Physically-Based Character Simulation) - 2021 Spring
부제가 작년과는 달라졌습니다. 확인해서 수정하기 바랍니다.

2021-07-15 21:39 UTC, yssl commented on publications-eng.js
> +	{
이 부분이 들어있는 걸 보니 master branch에서 git pull을 하지 않아 과거 코드 기반으로 PR을 만들었군요.
다시 최신 코드 기반으로 PR을 만들어 이미 반영되어 있는 변경사항이 PR에 포함되지 않도록 해주기 바랍니다.

2021-07-16 05:00 UTC, DiKaliZy commented on publications-eng.js
> +	{
수정 했습니다

2021-07-16 07:18 UTC, thscowns commented
수정된 것을 확인하였고, 문제없이 동작하는 것을 확인하였습니다.

2021-07-19 07:29 UTC, merged