2021-spring CG course
cgrhyu/cgrhyu.github.io pull request #25
Opened 2021-07-19 09:18 UTC by palkan21

2021년 1학기 컴퓨터그래픽스 페이지를 업데이트하고
3-courses.md의 conflict를 수정했습니다.

2021-07-20 05:25 UTC, thscowns commented on courses/2021-spring-cg.md
> +[12 - More Lighting, Texture]: https://gitcgr.hanyang.ac.kr/courses/2021-spring-cg/lecture-slides/12-MoreLighting,Texture.pdf
링크 확인해주세요

2021-07-20 05:25 UTC, thscowns commented on courses/2021-spring-cg.md
> +[13 - Rasterization & Visibility]: https://gitcgr.hanyang.ac.kr/courses/2021-spring-cg/lecture-slides/13-Rasterization&Visibility.pdf
링크 확인해주세요

2021-07-20 05:25 UTC, thscowns commented on courses/2021-spring-cg.md
> +|Topics   | Reference Materials |
다른 과목들 보면 date도 적혀있던데 이거는 필요없을까요??

2021-07-20 05:26 UTC, thscowns commented on courses/2021-spring-cg.md
> +[13 - Rasterization & Visibility]: https://gitcgr.hanyang.ac.kr/courses/2021-spring-cg/lecture-slides/13-Rasterization&Visibility.pdf
12 - more lighting, 13 -rasterization 링크가 작동하지 않는 것 같습니다.

2021-07-20 05:48 UTC, yssl commented on courses/2021-spring-cg.md
> +|Topics   | Reference Materials |
이건 제가 얘기한 사항입니다. 앞으로는 week와 date는 굳이 강의페이지에 넣지 않으려고 하거든요.

2021-07-20 17:23 UTC, palkan21 commented on courses/2021-spring-cg.md
> +[13 - Rasterization & Visibility]: https://gitcgr.hanyang.ac.kr/courses/2021-spring-cg/lecture-slides/13-Rasterization&Visibility.pdf
12 - more lighting, 13 -rasterization 링크가 작동하도록 수정했습니다.
(코드 변경 없이 database의 파일 이름 변경했습니다)

2021-07-21 00:36 UTC, yssl requested changes

2021-07-21 00:36 UTC, yssl commented on courses/2021-spring-cg.md
> +
여기에 `<br/>` 하나 넣읍시다.

2021-07-21 00:36 UTC, yssl commented on courses/2021-spring-cg.md
> +|Topics   | Reference Materials |
| Lecture #  | Lecture / Lab Topics  | Reference Materials  | 로 변경하도록 하죠.
아래 테이블 내용에서 Lecture #에 해당하는 첫 번째 컬럼은 그냥 숫자로 1, 2, 3... 순서대로 적어주면 되구요
미안하지만 | Lecture / Lab Topics  |  컬럼의 항목들은 링크를 걸지 않는 ', Lab Assignment X' 혹은 '/ Lab Assignment X'도 다시 예년과 같이 넣어주세요. 그게 더 많은 정보를 줄 수 있어 나을 것 같아요.

2021-07-21 00:41 UTC, yssl requested changes

2021-07-21 00:41 UTC, yssl commented on courses/2021-spring-cg.md
> +* Undergraduate Mentor: Sa, Zheng
Si Zheng으로 수정해주세요.

2021-07-22 00:26 UTC, palkan21 commented on courses/2021-spring-cg.md
> +* Undergraduate Mentor: Sa, Zheng
말씀하신 3가지 사항 변경해서 다시 commit 했습니다.

2021-07-22 12:33 UTC, thscowns commented
문제 없는 것 같습니다.

2021-07-25 08:54 UTC, merged