add 2022 kcgs extended abstract(kim minkwan)
cgrhyu/cgrhyu.github.io pull request #29
Opened 2022-07-19 11:04 UTC by palkan21

kcgs 2022 extended abstract 관련해서 업데이트했습니다.

2022-07-19 20:39 UTC, yssl requested changes
- 일단 작은 크기로 보이는 thumbnail로 하기에는 너무 많은 포즈가 들어갑니다. 제 생각에는 포즈 3개 정도, 구체적으로는 3행 1열, 2열, 4열 이미지 3개를 이어붙인 이미지 하나로 만드는 것이 좋을 것 같네요.
- 이미지 파일의 확장자 대소문자가 안 맞아서 이미지 렌더링이 안 되네요. 소문자로 변경해주세요. PR 제출 전에 꼭 로컬에서 jekyll 돌려서 페이지를 확인해봐야 합니다.
- 변경된 정책에 따라 이미지 크기를 100KB보다 작게 해주세요.

2022-07-21 23:26 UTC, yssl commented
Close 할 것 없이 PR을 업데이트 하면 됩니다.

2022-07-22 01:34 UTC, palkan21 commented
말씀하신 수정 사항 반영했습니다.
제 환경에서는 jekyll serve로 페이지 확인 했는데 혹시 문제 있으면 말씀 부탁 드립니다.

2022-07-22 04:42 UTC, yssl approved these changes

2022-07-22 04:43 UTC, merged