kcgs 2022 발표자료 publication-kor 추가
cgrhyu/cgrhyu.github.io pull request #30
Opened 2022-07-20 03:02 UTC by DiKaliZy

이미지와 pdf는 아직 서버에 업로드되지 않아 확인되지 않습니다.
(페이지에 내용이 정상적으로 반영되었기에 미리 pull request합니다)

2022-07-20 03:33 UTC, jmmhappy requested changes
representative image는 파일 스테이션에 업로드 하는게 아니라, 포크 하신 레퍼지토리의 assets/publications/domestic 폴더 안에 바로 넣어서 git add/commit/push 해주세요~

2022-07-20 03:35 UTC, jmmhappy commented
Personal page 에는 (논문 초록이나 이미지 )업데이트 안하시는 건가요?

2022-07-20 03:39 UTC, jmmhappy submitted a review, later dismissed

2022-07-20 03:41 UTC, DiKaliZy commented
말씀하신 부분 수정 완료했습니다

2022-07-20 03:43 UTC, jmmhappy commented
@yssl 교수님께서 확인해주시면 머지하겠습니다.

2022-07-21 23:31 UTC, yssl approved these changes

2022-07-21 23:31 UTC, merged