Add 2023 poster
cgrhyu/cgrhyu.github.io pull request #48
Opened 2023-06-16 06:20 UTC by yssl

- Add 2023 learning human-like poster
- Add CG lec 13 slide

2023-06-16 15:15 UTC, tth-97 requested changes
포스터 제출 연도 확인 부탁드립니다

2023-06-16 15:15 UTC, tth-97 commented on publications-eng.js
> +		'conference_journal_full': 'To be appeared in SIGGRAPH 2022 Posters',
연도(2022) 확인 부탁드립니다.

2023-06-17 01:01 UTC, yssl commented on publications-eng.js
> +		'conference_journal_full': 'To be appeared in SIGGRAPH 2022 Posters',
맞네요 수정해서 다시 올렸습니다 확인해주세요

2023-06-17 09:43 UTC, tth-97 approved these changes

2023-06-17 09:55 UTC, merged