kcgs 2023 발표 논문 update
cgrhyu/cgrhyu.github.io pull request #56
Opened 2023-08-14 01:37 UTC by DiKaliZy

kcgs2023 발표 내역 추가했습니다

2023-08-14 05:20 UTC, tth-97 requested changes
gitlab 서버 주소가 잘못된 것 같습니다(404 에러). 확인부탁드립니다.

2023-08-14 05:20 UTC, tth-97 commented on people/geuntae-park.md
> +**[사용자 멀티 터치 입력을 통한 캐릭터 이동 모션 생성](https://gitcgr.hanyang.ac.kr/publications/domestic/2023-kcgs-MultiTouch.pdf)**<br>
gitlab 서버 주소가 잘못된 것 같습니다(404 에러). 확인부탁드립니다.

2023-08-17 09:03 UTC, DiKaliZy commented on people/geuntae-park.md
> +**[사용자 멀티 터치 입력을 통한 캐릭터 이동 모션 생성](https://gitcgr.hanyang.ac.kr/publications/domestic/2023-kcgs-MultiTouch.pdf)**<br>
gitcgr에 파일 업로드했습니다

2023-08-17 17:39 UTC, tth-97 approved these changes

2023-08-17 23:31 UTC, yssl requested changes
conflict resolve해주세요

2023-08-18 01:31 UTC, DiKaliZy commented
수정했습니다

2023-08-18 02:00 UTC, yssl approved these changes

2023-08-18 02:00 UTC, merged