Jmmhappy
cgrhyu/cgrhyu.github.io pull request #7
Opened 2020-09-22 08:12 UTC by jmmhappy

jmmhappy: journalkcgs2020-luxo

2020-09-23 09:42 UTC, thscowns commented
음 PR 체크해봤는데 publication에서 in Korean 누르면 아무 반응이 없습니다.
문제가 생긴것 같아요!

2020-09-29 05:39 UTC, thscowns commented
확인 완료했습니다.

2020-09-30 08:26 UTC, yssl requested changes
1) publications-kor.js를 제외한 다른 파일의 변경사항은 이미 repository에 반영된 내용입니다.
즉, 새로 PR을 작성할 때 local repository가 최신의 code로 pull되지 않았던 상태였던 것 같네요.
git pull로 local repo를 최신 상태로 만든 후 다시 PR을 올려주세요.

2) 그리고 publications 페이지에는 최근 논문일 수록 상단에 표시되어야 합니다. js 파일에서 해당 논문 부분의 위치를 수정해주세요.

2020-10-01 14:51 UTC, jmmhappy commented
안녕하세요, git pull로 레포를 최신 상태로 만든 후 js 파일 수정 하였습니다.
제 로컬에서는 근태님 논문과 제 논문 모두 보이고 결과가 괜찮은 것 같은데 확인 부탁드립니다. 번거롭게 해드려 죄송합니다, 감사합니다!

2020-10-05 18:11 UTC, thscowns commented
1. people 페이지에서 최신 결과가 반영되었음을 확인했습니다.

2.  추가된 논문이 korean에서 가장 상당에 위치함을 확인했습니다.

제가 정확히 무엇을 확인해야 했는지 잘 모르는 상태였던것 같습니다. 
지적해 주신 부분에 대해서는 문제없고, 홈페이지의 모든 것이 정상적으로 돌아갑니다.

2020-10-07 23:39 UTC, merged