add_ksc2023_paper
cgrhyu/cgrhyu.github.io pull request #76
Opened 2023-12-28 03:36 UTC by tth-97

2023-12-30 21:51 UTC, yssl requested changes
comment 참고해서 수정해주세요.

2023-12-30 21:51 UTC, yssl commented on assets/publications/domestic/2023-ksc-toss-and-load.png
연구실 위키의 아래 지침을 참고해서, 이미지 용량을 조절해서 다시 올려주세요.

'Publications & Presentations' 페이지와 'People' 페이지의 thumbnail로 들어갈 이미지 파일은 100KB 보다 작은 크기로 만든다. 참고로 해당 페이지의 thumbnail은 220 x 124 픽셀 크기의 사각형 영역 안에 (비율을 유지하며) 가득 채워지도록 그려지므로, 이미지 파일이 220 x 124 보다 크기만 하면 된다.

2023-12-30 21:51 UTC, yssl commented on publications-kor.js
> +        'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2023-ksc-toss-and-load.pdf">[article]</a>',
제 PR#77을 보면 알 수 있는데, 앞으로 [article] 링크 등은 클릭할  경우 새 창(탭)에서 띄우는 식으로 하려고 합니다.
따라서 rel="noopener noreferrer" target="_blank" 를 추가해주세요. 
아래의 PR#77을 참고하면 됩니다.
https://github.com/cgrhyu/cgrhyu.github.io/pull/77/files#diff-86d482504ac9853ccb3f9ba69b8fc414685a88061c02f6fd840648109bd9c61b

2023-12-30 22:00 UTC, yssl commented on publications-kor.js
> +        'additional': '<a href="https://gitcgr.hanyang.ac.kr/publications/domestic/2023-ksc-toss-and-load.pdf">[article]</a>',
그리고 논문 파일도 프로시딩의 파일 (15-423.pdf)로 교체하는 것이 나을 것 같아요.
단 파일 이름은 15-423.pdf으로 하지 말고, 다시 2023-ksc-toss-and-load.pdf으로 rename해주세요.

2023-12-31 02:56 UTC, tth-97 commented on assets/publications/domestic/2023-ksc-toss-and-load.png
네, 용량 조절하여 다시 올렸습니다.

2023-12-31 03:05 UTC, yssl approved these changes

2023-12-31 03:05 UTC, merged