Jmmhappy
cgrhyu/cgrhyu.github.io pull request #8
Opened 2020-12-29 15:26 UTC by jmmhappy

2021-01-05 12:06 UTC, thscowns commented
1. course를 눌렀을 때, 2020 fall에 해당 과목이 뜨지 않습니다.
2. 가장 최신의 홈페이지가 아니어서 merge 후에 다시 부탁드립니다.

2021-01-06 07:55 UTC, jmmhappy commented
수정했습니다 확인 부탁드립니다.

2021-01-06 12:15 UTC, thscowns commented
확인 완료했습니다.

2021-01-06 20:24 UTC, yssl requested changes

2021-01-06 20:24 UTC, yssl commented on courses/2020-fall-csd.md
> +* Time / Location:
이 부분 설명 2020년 1학기 소입설 강의 페이지 참고해서 수정해주세요.

2021-01-06 20:24 UTC, yssl commented on courses/2020-fall-csd.md
> +* Teaching Assistant: Jeongmin Lee
정민 학생 개인 페이지 링크를 걸지 그래요?

2021-01-06 20:24 UTC, yssl commented on courses/2020-fall-csd.md
> +## Schedule
아래 스케쥴에 제목이 틀리거나 링크가 깨진 것이 다수 있으니 수정하기 바랍니다.

2021-01-07 23:27 UTC, yssl requested changes

2021-01-07 23:27 UTC, yssl commented on courses/2020-fall-csd.md
> +| 8  | Oct 27 / Oct 30, 31 | [8 - Inheritance, Const & Class] / Assignment 8 | |
여기서부터 주차가 밀렸네요. 9주차부터로 고쳐주세요.

2021-01-07 23:27 UTC, yssl commented on courses/2020-fall-csd.md
> +| 8  | Oct 20 / Oct 23, 24 | Midterm Exam  | |
Midterm Exam Week으로 수정해주세요.

2021-01-08 13:06 UTC, jmmhappy commented on courses/2020-fall-csd.md
> +| 8  | Oct 20 / Oct 23, 24 | Midterm Exam  | |
Final Exam은 그대로 두어도 괜찮은가요? 수정 완료 해두었습니다, 번거롭게 거듭 확인을 부탁드려 죄송합니다.

2021-01-08 22:32 UTC, yssl commented on courses/2020-fall-csd.md
> +| 8  | Oct 20 / Oct 23, 24 | Midterm Exam  | |
네 수고했습니다 채준학생 merge 해주세요.

2021-01-09 08:16 UTC, merged