Add 2024-matching-drl page
cgrhyu/cgrhyu.github.io pull request #88
Opened 2024-04-17 05:16 UTC by jmmhappy

2024 Euro short paper 에 제출한 논문의 간단한 프로젝트 페이지와 사소한 개인 페이지 수정입니다.
로컬 서버에서 잘 동작함을 확인하였습니다. 감사합니다.

2024-04-17 16:18 UTC, tth-97 submitted a review, later dismissed

2024-04-19 19:06 UTC, yssl requested changes
코멘트 반영해주세요~

2024-04-19 19:06 UTC, yssl commented on publications/2024-matching-drl.md
> +Open access paper: [pdf](https://arxiv.org/pdf/2403.15902) (610KB)
Open access paper: [pdf] 대신 arXiv: [arXiv page] 로 변경해주세요.

2024-04-19 19:06 UTC, yssl commented on publications/2024-matching-drl.md
> +Eurographics Short Papers (2024)
Eurographics 2024 Short Papers 로 수정해주세요.

2024-04-19 19:06 UTC, yssl commented on publications/2024-matching-drl.md
> +[Jeongmin Lee](../people/jeongmin-lee.html), [Taesoo Kwon](http://calab.hanyang.ac.kr/cgi-bin/home.cgi?node=Taesoo), [Yoonsang Lee](../people/yoonsang-lee.html)
모든 저자가 기입되지 않았네요.

2024-04-19 19:06 UTC, yssl commented on publications-eng.js
>          'additional': '<a href="https://arxiv.org/abs/2403.15902" rel="noopener noreferrer" target="_blank">[arXiv]</a> <a href="https://youtu.be/kR47MrPhJGk" rel="noopener noreferrer" target="_blank
하는 김에 [publisher link]도 넣어주세요 ㅎㅎ

2024-04-28 14:22 UTC, jmmhappy commented
pptx 및 수정사항 추가하여 force push 하였습니다 :)

2024-04-29 18:36 UTC, yssl approved these changes

2024-04-29 18:38 UTC, merged