Jeongmin Lee: publication added(LUXO)w
cgrhyu/cgrhyu.github.io pull request #9
Opened 2021-02-14 13:16 UTC by jmmhappy

doi 주소와 논문 이름을 people 의 개인 페이지에 추가했습니다.

2021-02-17 16:54 UTC, thscowns commented
네 확인했습니다. 
그런데 link의 위치가 사진 아래쪽에 위치해서 이걸 수정을 해야할지 확인하고 merge하겠습니다.

2021-02-17 23:34 UTC, yssl requested changes
개인페이지니 왠만하면 merge하라고 하려고 했지만, 돌려보니 레이아웃이 너무 안 맞네요. (채준학생 얘기를 돌려보니 이해하겠네요)
Publication 이라는 제목과 아래 적은 논문 내용이 완전히 분리되어 보입니다. 이건 고쳐야할 것 같아요.
그리고 논문 정보를 적을 때는 보통 저자, 어느 학회 or 논문지인지 등등의 정보를 함께 적는데, 같이 적는게 낫지 않을까 싶어요. 연구실 홈페이지 publication의 정보를 참고하세요.

2021-02-24 18:39 UTC, thscowns commented
죄송합니다만.. pull한번 다시 해주세요.
늦게 확인해서 죄송합니다.

2021-02-24 23:16 UTC, jmmhappy commented
Pull 은 제가 데이터를 가져오는 거 아닌가요?!
This branch has no conflicts with the base branch라고 되어 있는데 머지가 안되나요?

2021-02-25 23:32 UTC, thscowns commented
아.. 그 김민관학생 정보가 보이지 않아서 최신상태로 업데이트 해주세요.

2021-02-26 00:27 UTC, jmmhappy commented
머지했습니다~!

2021-02-26 05:52 UTC, thscowns commented
감사합니다. 제대로 된것 같습니다.

2021-03-02 03:53 UTC, merged