add kcgs 2024 multi-touch
cgrhyu/cgrhyu.github.io pull request #94
Opened 2024-07-29 12:06 UTC by DiKaliZy

2024-08-01 12:16 UTC, jbok6825 approved these changes

2024-08-02 03:14 UTC, yssl requested changes

2024-08-02 03:14 UTC, yssl commented on assets/publications/domestic/2024-kcgs-MultiTouch.png
연구실 위키의 homepage 설명을 참고해서 이미지 용량과 크기를 조절해주세요.

2024-08-02 04:24 UTC, DiKaliZy commented
크기 조절 완료했습니다

2024-08-02 10:46 UTC, yssl approved these changes

2024-08-02 10:46 UTC, merged