add kcgs 2024 dribble add kcgs 2024 latent matching (+resize image)
cgrhyu/cgrhyu.github.io pull request #98
Opened 2024-08-05 07:46 UTC by hhebb

+ resized image under 100 kb

2024-08-07 01:58 UTC, jbok6825 submitted a review, later dismissed

2024-08-08 00:00 UTC, yssl requested changes

2024-08-08 00:00 UTC, yssl commented on assets/publications/domestic/2024-kcgs-latent-matching.png
둘 다 이미지 품질이 너무 안 좋은데요? 이미지 크기 및 용량이 얼마 이하가 되어야 한다는 것은 이미지 품질과는 별개의 이야기입니다.

2024-08-09 07:01 UTC, hhebb commented on 1-people.md
> +</div>
확인해보니 불필요한 태그가 실수로 추가된것 같습니다.
제거하고 다시 push 하였습니다

2024-08-09 07:01 UTC, hhebb commented on 1-people.md
> +</div>
그리고 낮은 퀄리티의 이미지를 더 나은 이미지로 업데이트 하고 push 하였습니다

2024-08-09 07:02 UTC, hhebb commented on assets/publications/domestic/2024-kcgs-latent-matching.png
낮은 퀄리티의 이미지를 더 나은 이미지로 업데이트 하고 push 하였습니다

2024-08-11 05:49 UTC, yssl submitted a review, later dismissed

2024-08-11 05:50 UTC, yssl approved these changes

2024-08-11 05:50 UTC, merged